# %YAML:1.0

# Common parameters
cam_left_topic : "/kitti/camera_gray_left/image"
cam_right_topic: "/kitti/camera_gray_right/image"

camera_left: 
   image_width: 1241
   image_height: 376
   distortion_parameters:
      k1: 0
      k2: 0
      p1: 0
      p2: 0
   projection_parameters:
      fx: 718.8560
      fy: 718.8560
      cx: 607.1928
      cy: 185.2157

camera_right: 
   image_width: 1382
   image_height: 512
   distortion_parameters:
      k1: 0
      k2: 0
      p1: 0
      p2: 0
   projection_parameters:
      fx: 718.8560
      fy: 718.8560
      cx: 607.1928
      cy: 185.2157


# Following:
# - https://github.com/yanii/kitti-pcl/blob/master/KITTI_README.TXT
# - http://ww.cvlibs.net/publications/Geiger2013IJRR.pdf
# - Simple config download description: https://idorobotics.com/2019/05/29/converting-the-kitti-dataset-to-rosbags/
stereo:
   rotation:
      r11: 9.993440e-01
      r12: 1.814887e-02
      r13: -3.134011e-02
      r21: -1.842595e-02
      r22: 9.997935e-01
      r23: -8.575221e-03
      r31: 3.117801e-02
      r32: 9.147067e-03
      r33: 9.994720e-01
   translation:
      t1: -5.370000e-01
      t2: 5.964270e-03
      t3: -1.274584e-02