#!/usr/bin/env bash
set -euxo pipefail

mkdir -p ~/software
cd ${SOFTWARE_DIR}

sudo apt-get update
sudo apt-get upgrade -y

sudo apt install -y curl

# Install pip
sudo apt install -y python3-pip

if [[ "${VERSION_ID}" == "20.04" ]]; then
  sudo add-apt-repository universe
    sudo apt update 
    sudo apt install -y python2
    curl https://bootstrap.pypa.io/2.7/get-pip.py --output get-pip.py
    chmod +x get-pip.py
    sudo python2 get-pip.py
else
    sudo apt install -y python-pip
fi

pip install --upgrade pip

pip install numpy
pip install pandas
pip install matplotlib
pip install pillow
pip install scipy
pip install -U latex
pip install colorama
pip install pyyaml
pip install ruamel.yaml

sudo apt-get install -y python-tk

# VScode
sudo snap install --classic code

# Fonts for visualization 
sudo apt install -y texlive-fonts-recommended texlive-fonts-extra
sudo apt install -y dvipng

# Install Point cloud library
# sudo apt install libpcl-dev
# sudo apt-get install ros-melodic-pcl-conversions ros-melodic-pcl-ros
# Alternative PCL download: https://itectec.com/ubuntu/ubuntu-how-to-install-point-cloud-library-v1-8-pcl-1-8-0-on-ubuntu-16-04-2-lts-for-c-closed/
