#!/usr/bin/env bash
set -euxo pipefail

command -v sudo > /dev/null 2>&1 || { apt update && apt install --no-install-recommends -y sudo; }

cd ${SOFTWARE_DIR}

# Install Eigen and friends
if [[ "${VERSION_ID}" == "18.04" ] || [ "${VERSION_ID}" == "20.04" ]]; then
  sudo apt update && sudo apt install -y \
  libblas-dev \
  liblapack-dev \
  libeigen3-dev
else
  tag=${Eigen_VERSION:-3.3.4}
  sudo apt update && sudo apt install -y \
    cmake \
    curl \
    liblapack-dev
  curl -fsL https://gitlab.com/libeigen/eigen/-/archive/${tag}/eigen-${tag}.tar.gz \
  | tar -zx
  mv eigen* eigen-${tag}
  mkdir -p ./eigen-${tag}/build
  cd ./eigen-${tag}/build
  cmake .. -DCMAKE_BUILD_TYPE=Release
  cmake --build . --target blas
  sudo cmake --build . --target install
  cd blas
  sudo cmake --build . --target install
fi

