#!/usr/bin/env bash
topdir=$(pwd)
set -euxo pipefail

command -v sudo > /dev/null 2>&1 || { apt update && apt install --no-install-recommends -y sudo; }

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
${SCRIPT_DIR}/02-install-eigen

cd ${SOFTWARE_DIR}

sudo apt update && sudo apt install -y \
  build-essential \
  git \
  cmake

[[ ! -d "Sophus" ]] && git clone --depth 1 https://github.com/strasdat/Sophus.git

mkdir -p ./Sophus/build
cd ./Sophus/build
cmake .. \
  -DCMAKE_BUILD_TYPE=Release \
  -DBUILD_EXAMPLES=OFF \
  -DBUILD_TESTS=OFF
cmake --build . 
sudo cmake --build . --target install

cd ${topdir}
rm -rf Sophus ~/.cmake/packages/Sophus

# Alternative? http://wiki.ros.org/sophus
# sudo apt-get install ros-melodic-sophus