#!/usr/bin/env bash
set -euxo pipefail

topdir=$(pwd)
tag=${GGLIB_VERSION:-1.51}

command -v sudo > /dev/null 2>&1 || { apt update && apt install --no-install-recommends -y sudo; }

cd ~/software

sudo apt install -y \
  build-essential \
  cmake \
  curl \
  wget  # wget for geographiclib-get-geoids

curl -fsL https://sourceforge.net/projects/geographiclib/files/distrib/GeographicLib-${tag}.tar.gz \
| tar --xform 's/GeographicLib[0-9.-]+/geographiclib/gx' -zx

mkdir -p geographiclib/build
cd $_
cmake .. -DCMAKE_BUILD_TYPE=Release
sudo cmake --build . --config release --target install
sudo rm -rf geographiclib

cd ${topdir}
