#!/usr/bin/env bash
set -euxo pipefail
command -v sudo > /dev/null 2>&1 || function sudo { eval $@ ; }

sudo apt-get update
sudo apt-get upgrade -y

sudo apt install -y python-pip
sudo apt install -y python3-pip
pip install --upgrade pip


pip install numpy
pip install pandas
pip install matplotlib
pip install pillow
pip install scipy


sudo snap install --classic code


# Install Point cloud library
# sudo apt install libpcl-dev
# sudo apt-get install ros-melodic-pcl-conversions ros-melodic-pcl-ros
# Alternative PCL download: https://itectec.com/ubuntu/ubuntu-how-to-install-point-cloud-library-v1-8-pcl-1-8-0-on-ubuntu-16-04-2-lts-for-c-closed/
