#!/usr/bin/env bash
set -euxo pipefail
command -v sudo > /dev/null 2>&1 || { apt -qq update && apt install --no-install-recommends -y sudo; }

cd ~/software

# Following https://laurentkneip.github.io/opengv/page_installation.html
sudo apt-get install build-essential
sudo apt-get install cmake
sudo apt-get install cmake libeigen3-dev

git clone https://github.com/laurentkneip/opengv
cd opengv
mkdir build && cd build && cmake .. && make -j$(nproc)
